spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  jpa:
    properties:
      format_sql: true
      hibernate:
        show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      platform: h2
server:
  port: 8080